service: ClientDeployService

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  profile: ahwongcc

plugins:
  - serverless-client-s3

custom:
  client:
    bucketName: quorum.cloud.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}